// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

            

            

            @freezed
                sealed class WanError with _$WanError implements FrbException {
                    const WanError._();

                     /// 协议封包/解包错误
const factory WanError.protocol(  String field0,) = WanError_Protocol;
 /// BLE 扫描/连接/读写错误
const factory WanError.bluetooth(  String field0,) = WanError_Bluetooth;
 /// 音频采集/分析错误
const factory WanError.audio(  String field0,) = WanError_Audio;
 /// 参数非法
const factory WanError.invalid(  String field0,) = WanError_Invalid;

                    

                    
                }
            