// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/protocol.dart';
import 'dart:async';
import 'dart:convert';
import 'error.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiSimpleInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.12.0';

                  @override
                  int get rustContentHash => -1207780410;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'wan_protocol_frb',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<Uint8List> crateApiProtocolAntifakeInstruction({required int seq , required String macHex , required List<int> random16 });

Future<String> crateApiProtocolApiAesDecryptHex({required String ciphertextHex });

Future<String> crateApiProtocolApiAesEncryptHex({required String plaintext });

Future<Uint8List> crateApiProtocolBuildAndroidBroadcast({required int seq , required String macHex , required int region , required int x0 , required int y0 , required int show_ });

Future<IosBroadcastResult> crateApiProtocolBuildIosBroadcast({required int counter , required String macHex , required int region , required int x0 , required int y0 , required int show_ });

Future<Uint8List> crateApiProtocolBuildOtaFirmwarePacket({required int offset , required List<int> chunk });

Future<Uint8List> crateApiProtocolBuildOtaModeSwitch();

Future<Uint8List> crateApiProtocolBuildOtaReboot();

Future<String> crateApiProtocolBuildPacket({required int seq , required String commandBodyHex });

Future<String> crateApiProtocolBytesToHex({required List<int> bytes });

Future<int> crateApiProtocolCrc32Hex({required String hex });

Future<int> crateApiProtocolCrc32Ieee({required List<int> data });

Future<String> crateApiProtocolDec2Hex({required BigInt n , required int width });

Future<String> crateApiProtocolFrameSeqHexLe({required int seq });

Future<Uint8List> crateApiProtocolHexToBytes({required String hex });

Future<void> crateApiSimpleInitApp();

Future<List<String>> crateApiProtocolIosDataToServiceUuids({required List<int> data });

Future<String> crateApiProtocolLightFlashHex();

Future<String> crateApiProtocolLightingCommandBody({required LightingEffect effect , required String colorHex , required int seed });

Future<String> crateApiProtocolLittleEndian({required String hex });

Future<String> crateApiProtocolReportAesDecrypt({required String b64 });

Future<String> crateApiProtocolReportAesEncrypt({required String plaintext });

Future<String> crateApiProtocolSeatUnbindHex();

Future<String> crateApiProtocolSeatWriteHex({int? lightArea , required int x1 , required int y1 , int? showNum });

Future<bool> crateApiProtocolVerifyAntifake({required List<int> message , required List<int> signature , required List<int> publicKey });


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<Uint8List> crateApiProtocolAntifakeInstruction({required int seq , required String macHex , required List<int> random16 })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(seq, serializer);
sse_encode_String(macHex, serializer);
sse_encode_list_prim_u_8_loose(random16, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolAntifakeInstructionConstMeta,
            argValues: [seq, macHex, random16],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolAntifakeInstructionConstMeta => const TaskConstMeta(
            debugName: "antifake_instruction",
            argNames: ["seq", "macHex", "random16"],
        );
        

@override Future<String> crateApiProtocolApiAesDecryptHex({required String ciphertextHex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(ciphertextHex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_wan_error,
        )
        ,
            constMeta: kCrateApiProtocolApiAesDecryptHexConstMeta,
            argValues: [ciphertextHex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolApiAesDecryptHexConstMeta => const TaskConstMeta(
            debugName: "api_aes_decrypt_hex",
            argNames: ["ciphertextHex"],
        );
        

@override Future<String> crateApiProtocolApiAesEncryptHex({required String plaintext })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(plaintext, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_wan_error,
        )
        ,
            constMeta: kCrateApiProtocolApiAesEncryptHexConstMeta,
            argValues: [plaintext],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolApiAesEncryptHexConstMeta => const TaskConstMeta(
            debugName: "api_aes_encrypt_hex",
            argNames: ["plaintext"],
        );
        

@override Future<Uint8List> crateApiProtocolBuildAndroidBroadcast({required int seq , required String macHex , required int region , required int x0 , required int y0 , required int show_ })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(seq, serializer);
sse_encode_String(macHex, serializer);
sse_encode_u_8(region, serializer);
sse_encode_u_16(x0, serializer);
sse_encode_u_16(y0, serializer);
sse_encode_u_8(show_, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildAndroidBroadcastConstMeta,
            argValues: [seq, macHex, region, x0, y0, show_],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildAndroidBroadcastConstMeta => const TaskConstMeta(
            debugName: "build_android_broadcast",
            argNames: ["seq", "macHex", "region", "x0", "y0", "show_"],
        );
        

@override Future<IosBroadcastResult> crateApiProtocolBuildIosBroadcast({required int counter , required String macHex , required int region , required int x0 , required int y0 , required int show_ })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_8(counter, serializer);
sse_encode_String(macHex, serializer);
sse_encode_u_8(region, serializer);
sse_encode_u_16(x0, serializer);
sse_encode_u_16(y0, serializer);
sse_encode_u_8(show_, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_ios_broadcast_result,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildIosBroadcastConstMeta,
            argValues: [counter, macHex, region, x0, y0, show_],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildIosBroadcastConstMeta => const TaskConstMeta(
            debugName: "build_ios_broadcast",
            argNames: ["counter", "macHex", "region", "x0", "y0", "show_"],
        );
        

@override Future<Uint8List> crateApiProtocolBuildOtaFirmwarePacket({required int offset , required List<int> chunk })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(offset, serializer);
sse_encode_list_prim_u_8_loose(chunk, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildOtaFirmwarePacketConstMeta,
            argValues: [offset, chunk],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildOtaFirmwarePacketConstMeta => const TaskConstMeta(
            debugName: "build_ota_firmware_packet",
            argNames: ["offset", "chunk"],
        );
        

@override Future<Uint8List> crateApiProtocolBuildOtaModeSwitch()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildOtaModeSwitchConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildOtaModeSwitchConstMeta => const TaskConstMeta(
            debugName: "build_ota_mode_switch",
            argNames: [],
        );
        

@override Future<Uint8List> crateApiProtocolBuildOtaReboot()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildOtaRebootConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildOtaRebootConstMeta => const TaskConstMeta(
            debugName: "build_ota_reboot",
            argNames: [],
        );
        

@override Future<String> crateApiProtocolBuildPacket({required int seq , required String commandBodyHex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(seq, serializer);
sse_encode_String(commandBodyHex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildPacketConstMeta,
            argValues: [seq, commandBodyHex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildPacketConstMeta => const TaskConstMeta(
            debugName: "build_packet",
            argNames: ["seq", "commandBodyHex"],
        );
        

@override Future<String> crateApiProtocolBytesToHex({required List<int> bytes })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_u_8_loose(bytes, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBytesToHexConstMeta,
            argValues: [bytes],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBytesToHexConstMeta => const TaskConstMeta(
            debugName: "bytes_to_hex",
            argNames: ["bytes"],
        );
        

@override Future<int> crateApiProtocolCrc32Hex({required String hex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(hex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolCrc32HexConstMeta,
            argValues: [hex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolCrc32HexConstMeta => const TaskConstMeta(
            debugName: "crc32_hex",
            argNames: ["hex"],
        );
        

@override Future<int> crateApiProtocolCrc32Ieee({required List<int> data })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_u_8_loose(data, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolCrc32IeeeConstMeta,
            argValues: [data],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolCrc32IeeeConstMeta => const TaskConstMeta(
            debugName: "crc32_ieee",
            argNames: ["data"],
        );
        

@override Future<String> crateApiProtocolDec2Hex({required BigInt n , required int width })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_64(n, serializer);
sse_encode_u_32(width, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolDec2HexConstMeta,
            argValues: [n, width],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolDec2HexConstMeta => const TaskConstMeta(
            debugName: "dec2hex",
            argNames: ["n", "width"],
        );
        

@override Future<String> crateApiProtocolFrameSeqHexLe({required int seq })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(seq, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolFrameSeqHexLeConstMeta,
            argValues: [seq],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolFrameSeqHexLeConstMeta => const TaskConstMeta(
            debugName: "frame_seq_hex_le",
            argNames: ["seq"],
        );
        

@override Future<Uint8List> crateApiProtocolHexToBytes({required String hex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(hex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolHexToBytesConstMeta,
            argValues: [hex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolHexToBytesConstMeta => const TaskConstMeta(
            debugName: "hex_to_bytes",
            argNames: ["hex"],
        );
        

@override Future<void> crateApiSimpleInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiSimpleInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override Future<List<String>> crateApiProtocolIosDataToServiceUuids({required List<int> data })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_u_8_loose(data, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolIosDataToServiceUuidsConstMeta,
            argValues: [data],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolIosDataToServiceUuidsConstMeta => const TaskConstMeta(
            debugName: "ios_data_to_service_uuids",
            argNames: ["data"],
        );
        

@override Future<String> crateApiProtocolLightFlashHex()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolLightFlashHexConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolLightFlashHexConstMeta => const TaskConstMeta(
            debugName: "light_flash_hex",
            argNames: [],
        );
        

@override Future<String> crateApiProtocolLightingCommandBody({required LightingEffect effect , required String colorHex , required int seed })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_lighting_effect(effect, serializer);
sse_encode_String(colorHex, serializer);
sse_encode_u_8(seed, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolLightingCommandBodyConstMeta,
            argValues: [effect, colorHex, seed],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolLightingCommandBodyConstMeta => const TaskConstMeta(
            debugName: "lighting_command_body",
            argNames: ["effect", "colorHex", "seed"],
        );
        

@override Future<String> crateApiProtocolLittleEndian({required String hex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(hex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolLittleEndianConstMeta,
            argValues: [hex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolLittleEndianConstMeta => const TaskConstMeta(
            debugName: "little_endian",
            argNames: ["hex"],
        );
        

@override Future<String> crateApiProtocolReportAesDecrypt({required String b64 })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(b64, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_wan_error,
        )
        ,
            constMeta: kCrateApiProtocolReportAesDecryptConstMeta,
            argValues: [b64],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolReportAesDecryptConstMeta => const TaskConstMeta(
            debugName: "report_aes_decrypt",
            argNames: ["b64"],
        );
        

@override Future<String> crateApiProtocolReportAesEncrypt({required String plaintext })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(plaintext, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolReportAesEncryptConstMeta,
            argValues: [plaintext],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolReportAesEncryptConstMeta => const TaskConstMeta(
            debugName: "report_aes_encrypt",
            argNames: ["plaintext"],
        );
        

@override Future<String> crateApiProtocolSeatUnbindHex()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolSeatUnbindHexConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolSeatUnbindHexConstMeta => const TaskConstMeta(
            debugName: "seat_unbind_hex",
            argNames: [],
        );
        

@override Future<String> crateApiProtocolSeatWriteHex({int? lightArea , required int x1 , required int y1 , int? showNum })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_opt_box_autoadd_u_8(lightArea, serializer);
sse_encode_u_16(x1, serializer);
sse_encode_u_16(y1, serializer);
sse_encode_opt_box_autoadd_u_8(showNum, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolSeatWriteHexConstMeta,
            argValues: [lightArea, x1, y1, showNum],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolSeatWriteHexConstMeta => const TaskConstMeta(
            debugName: "seat_write_hex",
            argNames: ["lightArea", "x1", "y1", "showNum"],
        );
        

@override Future<bool> crateApiProtocolVerifyAntifake({required List<int> message , required List<int> signature , required List<int> publicKey })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_list_prim_u_8_loose(message, serializer);
sse_encode_list_prim_u_8_loose(signature, serializer);
sse_encode_list_prim_u_8_loose(publicKey, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolVerifyAntifakeConstMeta,
            argValues: [message, signature, publicKey],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolVerifyAntifakeConstMeta => const TaskConstMeta(
            debugName: "verify_antifake",
            argNames: ["message", "signature", "publicKey"],
        );
        



                  @protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected int dco_decode_box_autoadd_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected IosBroadcastResult dco_decode_ios_broadcast_result(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return IosBroadcastResult(frmcnt: dco_decode_u_8(arr[0]),
data: dco_decode_list_prim_u_8_strict(arr[1]),); }

@protected LightingEffect dco_decode_lighting_effect(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return LightingEffect.values[raw as int]; }

@protected List<String> dco_decode_list_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_String).toList(); }

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected int? dco_decode_opt_box_autoadd_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw == null ? null : dco_decode_box_autoadd_u_8(raw); }

@protected int dco_decode_u_16(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected BigInt dco_decode_u_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected WanError dco_decode_wan_error(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
switch (raw[0]) {
                case 0: return WanError_Protocol(dco_decode_String(raw[1]),);
case 1: return WanError_Bluetooth(dco_decode_String(raw[1]),);
case 2: return WanError_Audio(dco_decode_String(raw[1]),);
case 3: return WanError_Invalid(dco_decode_String(raw[1]),);
                default: throw Exception("unreachable");
            } }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected int sse_decode_box_autoadd_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return (sse_decode_u_8(deserializer)); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected IosBroadcastResult sse_decode_ios_broadcast_result(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_frmcnt = sse_decode_u_8(deserializer);
var var_data = sse_decode_list_prim_u_8_strict(deserializer);
return IosBroadcastResult(frmcnt: var_frmcnt, data: var_data); }

@protected LightingEffect sse_decode_lighting_effect(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return LightingEffect.values[inner]; }

@protected List<String> sse_decode_list_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <String>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_String(deserializer)); }
        return ans_;
         }

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            if (sse_decode_bool(deserializer)) {
                return (sse_decode_box_autoadd_u_8(deserializer));
            } else {
                return null;
            }
             }

@protected int sse_decode_u_16(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint16(); }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected BigInt sse_decode_u_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected WanError sse_decode_wan_error(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

            var tag_ = sse_decode_i_32(deserializer);
            switch (tag_) { case 0: var var_field0 = sse_decode_String(deserializer);
return WanError_Protocol(var_field0);case 1: var var_field0 = sse_decode_String(deserializer);
return WanError_Bluetooth(var_field0);case 2: var var_field0 = sse_decode_String(deserializer);
return WanError_Audio(var_field0);case 3: var var_field0 = sse_decode_String(deserializer);
return WanError_Invalid(var_field0); default: throw UnimplementedError(''); }
             }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_8(self, serializer); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_ios_broadcast_result(IosBroadcastResult self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_u_8(self.frmcnt, serializer);
sse_encode_list_prim_u_8_strict(self.data, serializer);
 }

@protected void sse_encode_lighting_effect(LightingEffect self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_String(item, serializer); } }

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self)); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs

                sse_encode_bool(self != null, serializer);
                if (self != null) {
                    sse_encode_box_autoadd_u_8(self, serializer);
                }
                 }

@protected void sse_encode_u_16(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint16(self); }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_wan_error(WanError self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
switch (self) { case WanError_Protocol(field0: final field0): sse_encode_i_32(0, serializer); sse_encode_String(field0, serializer);
case WanError_Bluetooth(field0: final field0): sse_encode_i_32(1, serializer); sse_encode_String(field0, serializer);
case WanError_Audio(field0: final field0): sse_encode_i_32(2, serializer); sse_encode_String(field0, serializer);
case WanError_Invalid(field0: final field0): sse_encode_i_32(3, serializer); sse_encode_String(field0, serializer);
  } }
                }
                
