// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/audio.dart';
import 'api/lightstick.dart';
import 'api/protocol.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lightstick/effect.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


                /// Main entrypoint of the Rust API
                class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
                  @internal
                  static final instance = RustLib._();

                  RustLib._();

                  /// Initialize flutter_rust_bridge
                  static Future<void> init({
                    RustLibApi? api,
                    BaseHandler? handler,
                    ExternalLibrary? externalLibrary,
                    bool forceSameCodegenVersion = true,
                  }) async {
                    await instance.initImpl(
                      api: api,
                      handler: handler,
                      externalLibrary: externalLibrary,
                      forceSameCodegenVersion: forceSameCodegenVersion,
                    );
                  }

                  /// Initialize flutter_rust_bridge in mock mode.
                  /// No libraries for FFI are loaded.
                  static void initMock({
                    required RustLibApi api,
                  }) {
                    instance.initMockImpl(
                      api: api,
                    );
                  }

                  /// Dispose flutter_rust_bridge
                  ///
                  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
                  /// is automatically disposed when the app stops.
                  static void dispose() => instance.disposeImpl();

                  @override
                  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

                  @override
                  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

                  @override
                  Future<void> executeRustInitializers() async {
                    await api.crateApiSimpleInitApp();

                  }

                  @override
                  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig => kDefaultExternalLibraryLoaderConfig;

                  @override
                  String get codegenVersion => '2.12.0';

                  @override
                  int get rustContentHash => 2104180450;

                  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
                    stem: 'wan_protocol_frb',
                    ioDirectory: 'rust/target/release/',
                    webPrefix: 'pkg/',
                    wasmBindgenName: 'wasm_bindgen',
                  );
                }
                

                abstract class RustLibApi extends BaseApi {
                  Future<MusicRhythm> crateApiLightstickMusicRhythmCreate();

Future<LightOutput> crateApiLightstickMusicRhythmNext({required MusicRhythm that , required double volume });

Future<void> crateApiLightstickMusicRhythmSetBaseColor({required MusicRhythm that , required List<int> rgb });

Future<void> crateApiLightstickMusicRhythmSetMode({required MusicRhythm that , required RhythmMode mode });

Future<void> crateApiLightstickMusicRhythmSetSensitivity({required MusicRhythm that , required double v });

Future<PcmAnalyzer> crateApiAudioPcmAnalyzerCreate();

Future<List<AudioFrame>> crateApiAudioPcmAnalyzerPush({required PcmAnalyzer that , required List<int> chunk });

Future<String> crateApiProtocolBuildPacket({required int seq , required String commandBodyHex });

Future<Uint8List> crateApiProtocolHexToBytes({required String hex });

Future<void> crateApiSimpleInitApp();

Future<String> crateApiProtocolLightingCommandBody({required LightingEffect effect , required String colorHex , required int seed });

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_MusicRhythm;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_MusicRhythm;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_MusicRhythmPtr;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_PcmAnalyzer;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_PcmAnalyzer;

CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PcmAnalyzerPtr;


                }
                

                class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
                  RustLibApiImpl({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  @override Future<MusicRhythm> crateApiLightstickMusicRhythmCreate()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiLightstickMusicRhythmCreateConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLightstickMusicRhythmCreateConstMeta => const TaskConstMeta(
            debugName: "MusicRhythm_create",
            argNames: [],
        );
        

@override Future<LightOutput> crateApiLightstickMusicRhythmNext({required MusicRhythm that , required double volume })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(that, serializer);
sse_encode_f_64(volume, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_light_output,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiLightstickMusicRhythmNextConstMeta,
            argValues: [that, volume],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLightstickMusicRhythmNextConstMeta => const TaskConstMeta(
            debugName: "MusicRhythm_next",
            argNames: ["that", "volume"],
        );
        

@override Future<void> crateApiLightstickMusicRhythmSetBaseColor({required MusicRhythm that , required List<int> rgb })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(that, serializer);
sse_encode_list_prim_u_8_loose(rgb, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiLightstickMusicRhythmSetBaseColorConstMeta,
            argValues: [that, rgb],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLightstickMusicRhythmSetBaseColorConstMeta => const TaskConstMeta(
            debugName: "MusicRhythm_set_base_color",
            argNames: ["that", "rgb"],
        );
        

@override Future<void> crateApiLightstickMusicRhythmSetMode({required MusicRhythm that , required RhythmMode mode })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(that, serializer);
sse_encode_rhythm_mode(mode, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiLightstickMusicRhythmSetModeConstMeta,
            argValues: [that, mode],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLightstickMusicRhythmSetModeConstMeta => const TaskConstMeta(
            debugName: "MusicRhythm_set_mode",
            argNames: ["that", "mode"],
        );
        

@override Future<void> crateApiLightstickMusicRhythmSetSensitivity({required MusicRhythm that , required double v })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(that, serializer);
sse_encode_f_64(v, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiLightstickMusicRhythmSetSensitivityConstMeta,
            argValues: [that, v],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiLightstickMusicRhythmSetSensitivityConstMeta => const TaskConstMeta(
            debugName: "MusicRhythm_set_sensitivity",
            argNames: ["that", "v"],
        );
        

@override Future<PcmAnalyzer> crateApiAudioPcmAnalyzerCreate()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiAudioPcmAnalyzerCreateConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiAudioPcmAnalyzerCreateConstMeta => const TaskConstMeta(
            debugName: "PcmAnalyzer_create",
            argNames: [],
        );
        

@override Future<List<AudioFrame>> crateApiAudioPcmAnalyzerPush({required PcmAnalyzer that , required List<int> chunk })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(that, serializer);
sse_encode_list_prim_u_8_loose(chunk, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_audio_frame,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiAudioPcmAnalyzerPushConstMeta,
            argValues: [that, chunk],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiAudioPcmAnalyzerPushConstMeta => const TaskConstMeta(
            debugName: "PcmAnalyzer_push",
            argNames: ["that", "chunk"],
        );
        

@override Future<String> crateApiProtocolBuildPacket({required int seq , required String commandBodyHex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_u_32(seq, serializer);
sse_encode_String(commandBodyHex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolBuildPacketConstMeta,
            argValues: [seq, commandBodyHex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolBuildPacketConstMeta => const TaskConstMeta(
            debugName: "build_packet",
            argNames: ["seq", "commandBodyHex"],
        );
        

@override Future<Uint8List> crateApiProtocolHexToBytes({required String hex })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_String(hex, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolHexToBytesConstMeta,
            argValues: [hex],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolHexToBytesConstMeta => const TaskConstMeta(
            debugName: "hex_to_bytes",
            argNames: ["hex"],
        );
        

@override Future<void> crateApiSimpleInitApp()  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiSimpleInitAppConstMeta,
            argValues: [],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
            debugName: "init_app",
            argNames: [],
        );
        

@override Future<String> crateApiProtocolLightingCommandBody({required LightingEffect effect , required String colorHex , required int seed })  { return handler.executeNormal(NormalTask(
            callFfi: (port_) {
              
            final serializer = SseSerializer(generalizedFrbRustBinding);sse_encode_lighting_effect(effect, serializer);
sse_encode_String(colorHex, serializer);
sse_encode_u_8(seed, serializer);
            pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11, port: port_);
            
            },
            codec: 
        SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        )
        ,
            constMeta: kCrateApiProtocolLightingCommandBodyConstMeta,
            argValues: [effect, colorHex, seed],
            apiImpl: this,
        )); }


        TaskConstMeta get kCrateApiProtocolLightingCommandBodyConstMeta => const TaskConstMeta(
            debugName: "lighting_command_body",
            argNames: ["effect", "colorHex", "seed"],
        );
        

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_MusicRhythm => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_MusicRhythm => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm;

RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_PcmAnalyzer => wire.rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer;

RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_PcmAnalyzer => wire.rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer;



                  @protected MusicRhythm dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MusicRhythmImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected PcmAnalyzer dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PcmAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected MusicRhythm dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MusicRhythmImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected PcmAnalyzer dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PcmAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected MusicRhythm dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return MusicRhythmImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected PcmAnalyzer dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return PcmAnalyzerImpl.frbInternalDcoDecode(raw as List<dynamic>); }

@protected String dco_decode_String(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as String; }

@protected AudioFrame dco_decode_audio_frame(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
                return AudioFrame(volume: dco_decode_f_64(arr[0]),
bands: dco_decode_list_prim_f_64_strict(arr[1]),
bass: dco_decode_f_64(arr[2]),
treble: dco_decode_f_64(arr[3]),
isBeat: dco_decode_bool(arr[4]),); }

@protected bool dco_decode_bool(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as bool; }

@protected double dco_decode_f_64(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as double; }

@protected int dco_decode_i_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected LightOutput dco_decode_light_output(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
final arr = raw as List<dynamic>;
                if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
                return LightOutput(rgb: dco_decode_list_prim_u_8_strict(arr[0]),
brightness: dco_decode_f_64(arr[1]),); }

@protected LightingEffect dco_decode_lighting_effect(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return LightingEffect.values[raw as int]; }

@protected List<AudioFrame> dco_decode_list_audio_frame(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return (raw as List<dynamic>).map(dco_decode_audio_frame).toList(); }

@protected Float64List dco_decode_list_prim_f_64_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Float64List; }

@protected List<int> dco_decode_list_prim_u_8_loose(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as List<int>; }

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as Uint8List; }

@protected RhythmMode dco_decode_rhythm_mode(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return RhythmMode.values[raw as int]; }

@protected int dco_decode_u_32(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected int dco_decode_u_8(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return raw as int; }

@protected void dco_decode_unit(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return; }

@protected BigInt dco_decode_usize(dynamic raw){ // Codec=Dco (DartCObject based), see doc to use other codecs
return dcoDecodeU64(raw); }

@protected MusicRhythm sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MusicRhythmImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected PcmAnalyzer sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PcmAnalyzerImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected MusicRhythm sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MusicRhythmImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected PcmAnalyzer sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PcmAnalyzerImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected MusicRhythm sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return MusicRhythmImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected PcmAnalyzer sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return PcmAnalyzerImpl.frbInternalSseDecode(sse_decode_usize(deserializer), sse_decode_i_32(deserializer)); }

@protected String sse_decode_String(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_list_prim_u_8_strict(deserializer);
        return utf8.decoder.convert(inner); }

@protected AudioFrame sse_decode_audio_frame(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_volume = sse_decode_f_64(deserializer);
var var_bands = sse_decode_list_prim_f_64_strict(deserializer);
var var_bass = sse_decode_f_64(deserializer);
var var_treble = sse_decode_f_64(deserializer);
var var_isBeat = sse_decode_bool(deserializer);
return AudioFrame(volume: var_volume, bands: var_bands, bass: var_bass, treble: var_treble, isBeat: var_isBeat); }

@protected bool sse_decode_bool(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8() != 0; }

@protected double sse_decode_f_64(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getFloat64(); }

@protected int sse_decode_i_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getInt32(); }

@protected LightOutput sse_decode_light_output(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var var_rgb = sse_decode_list_prim_u_8_strict(deserializer);
var var_brightness = sse_decode_f_64(deserializer);
return LightOutput(rgb: var_rgb, brightness: var_brightness); }

@protected LightingEffect sse_decode_lighting_effect(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return LightingEffect.values[inner]; }

@protected List<AudioFrame> sse_decode_list_audio_frame(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs

        var len_ = sse_decode_i_32(deserializer);
        var ans_ = <AudioFrame>[];
        for (var idx_ = 0; idx_ < len_; ++idx_) { ans_.add(sse_decode_audio_frame(deserializer)); }
        return ans_;
         }

@protected Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getFloat64List(len_); }

@protected List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var len_ = sse_decode_i_32(deserializer);
                return deserializer.buffer.getUint8List(len_); }

@protected RhythmMode sse_decode_rhythm_mode(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
var inner = sse_decode_i_32(deserializer);
        return RhythmMode.values[inner]; }

@protected int sse_decode_u_32(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint32(); }

@protected int sse_decode_u_8(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getUint8(); }

@protected void sse_decode_unit(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected BigInt sse_decode_usize(SseDeserializer deserializer){ // Codec=Sse (Serialization based), see doc to use other codecs
return deserializer.buffer.getBigUint64(); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(MusicRhythm self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MusicRhythmImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(PcmAnalyzer self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PcmAnalyzerImpl).frbInternalSseEncode(move: true), serializer); }

@protected void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(MusicRhythm self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MusicRhythmImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(PcmAnalyzer self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PcmAnalyzerImpl).frbInternalSseEncode(move: false), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerMusicRhythm(MusicRhythm self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as MusicRhythmImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPcmAnalyzer(PcmAnalyzer self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_usize((self as PcmAnalyzerImpl).frbInternalSseEncode(move: null), serializer); }

@protected void sse_encode_String(String self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer); }

@protected void sse_encode_audio_frame(AudioFrame self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_f_64(self.volume, serializer);
sse_encode_list_prim_f_64_strict(self.bands, serializer);
sse_encode_f_64(self.bass, serializer);
sse_encode_f_64(self.treble, serializer);
sse_encode_bool(self.isBeat, serializer);
 }

@protected void sse_encode_bool(bool self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self ? 1 : 0); }

@protected void sse_encode_f_64(double self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putFloat64(self); }

@protected void sse_encode_i_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putInt32(self); }

@protected void sse_encode_light_output(LightOutput self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_list_prim_u_8_strict(self.rgb, serializer);
sse_encode_f_64(self.brightness, serializer);
 }

@protected void sse_encode_lighting_effect(LightingEffect self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_list_audio_frame(List<AudioFrame> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
        for (final item in self) { sse_encode_audio_frame(item, serializer); } }

@protected void sse_encode_list_prim_f_64_strict(Float64List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putFloat64List(self); }

@protected void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self is Uint8List ? self : Uint8List.fromList(self)); }

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.length, serializer);
                    serializer.buffer.putUint8List(self); }

@protected void sse_encode_rhythm_mode(RhythmMode self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
sse_encode_i_32(self.index, serializer); }

@protected void sse_encode_u_32(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint32(self); }

@protected void sse_encode_u_8(int self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putUint8(self); }

@protected void sse_encode_unit(void self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
 }

@protected void sse_encode_usize(BigInt self, SseSerializer serializer){ // Codec=Sse (Serialization based), see doc to use other codecs
serializer.buffer.putBigUint64(self); }
                }
                

            @sealed class MusicRhythmImpl extends RustOpaque implements MusicRhythm {
                // Not to be used by end users
                MusicRhythmImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                MusicRhythmImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_MusicRhythm,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_MusicRhythm,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_MusicRhythmPtr,
                );

                /// 由音量（0..1）推进一步，返回应下发的颜色与亮度。
 Future<LightOutput>  next({required double volume })=>RustLib.instance.api.crateApiLightstickMusicRhythmNext(that: this, volume: volume);


/// 单色律动的固定颜色（RGB 3 字节）。
 Future<void>  setBaseColor({required List<int> rgb })=>RustLib.instance.api.crateApiLightstickMusicRhythmSetBaseColor(that: this, rgb: rgb);


 Future<void>  setMode({required RhythmMode mode })=>RustLib.instance.api.crateApiLightstickMusicRhythmSetMode(that: this, mode: mode);


/// 灵敏度 0..1（亮度 = 音量 × 灵敏度）。
 Future<void>  setSensitivity({required double v })=>RustLib.instance.api.crateApiLightstickMusicRhythmSetSensitivity(that: this, v: v);


            }
            @sealed class PcmAnalyzerImpl extends RustOpaque implements PcmAnalyzer {
                // Not to be used by end users
                PcmAnalyzerImpl.frbInternalDcoDecode(List<dynamic> wire):
                    super.frbInternalDcoDecode(wire, _kStaticData);

                // Not to be used by end users
                PcmAnalyzerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative):
                    super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

                static final _kStaticData = RustArcStaticData(
                    rustArcIncrementStrongCount: RustLib.instance.api.rust_arc_increment_strong_count_PcmAnalyzer,
                    rustArcDecrementStrongCount: RustLib.instance.api.rust_arc_decrement_strong_count_PcmAnalyzer,
                    rustArcDecrementStrongCountPtr: RustLib.instance.api.rust_arc_decrement_strong_count_PcmAnalyzerPtr,
                );

                /// 喂入 PCM16 小端字节流，返回本次新产生的全部分析帧。
 Future<List<AudioFrame>>  push({required List<int> chunk })=>RustLib.instance.api.crateApiAudioPcmAnalyzerPush(that: this, chunk: chunk);


            }