// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            

            

            /// 律动模式。
enum RhythmMode {
                    /// 单色律动：固定 base 色。
single,
/// 七彩律动：15 色板循环。
rainbow,
/// 强烈：七彩 + 亮度增益。
strong,
/// 柔和：七彩 + 亮度压缩。
soft,
                    ;
                    
                }
            