// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PcmAnalyzer>>
                abstract class PcmAnalyzer implements RustOpaqueInterface {
                    /// 默认参数：28 频带、1024 窗、44.1kHz（与 record 采集配置一致）。
static Future<PcmAnalyzer>  create()=>RustLib.instance.api.crateApiAudioPcmAnalyzerCreate();


/// 喂入 PCM16 小端字节流，返回本次新产生的全部分析帧。
 Future<List<AudioFrame>>  push({required List<int> chunk });



                    
                }
                

/// 一帧音频分析结果：音量级 + 频带能量 + 低频/高频 + 节拍。
class AudioFrame  {
                /// 音量级 0..1（RMS + 动态峰值归一化）。
final double volume;
/// 频带能量 0..1（对数频带，长度 28）。
final Float64List bands;
/// 低频能量 0..1（约 40~230Hz）。
final double bass;
/// 高频能量 0..1（约 4kHz+）。
final double treble;
/// 强拍标记。
final bool isBeat;

                const AudioFrame({required this.volume ,required this.bands ,required this.bass ,required this.treble ,required this.isBeat ,});

                
                

                
        @override
        int get hashCode => volume.hashCode^bands.hashCode^bass.hashCode^treble.hashCode^isBeat.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is AudioFrame &&
                runtimeType == other.runtimeType
                && volume == other.volume&& bands == other.bands&& bass == other.bass&& treble == other.treble&& isBeat == other.isBeat;
        
            }
            