// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'audio.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`


            

            
                // Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MusicRhythm>>
                abstract class MusicRhythm implements RustOpaqueInterface {
                    static Future<MusicRhythm>  create()=>RustLib.instance.api.crateApiLightstickMusicRhythmCreate();


/// 由音频帧推进一步，返回应下发的颜色与亮度。
 Future<LightOutput>  next({required AudioFrame frame });


/// 单色律动的固定颜色（RGB 3 字节）。
 Future<void>  setBaseColor({required List<int> rgb });


 Future<void>  setMode({required RhythmMode mode });


/// 灵敏度 0..1（亮度 = 音量 × 灵敏度）。
 Future<void>  setSensitivity({required double v });



                    
                }
                

/// 一帧律动输出：RGB 颜色（3 字节）+ 亮度（0..1，随音量变化）。
class LightOutput  {
                final Uint8List rgb;
final double brightness;

                const LightOutput({required this.rgb ,required this.brightness ,});

                
                

                
        @override
        int get hashCode => rgb.hashCode^brightness.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is LightOutput &&
                runtimeType == other.runtimeType
                && rgb == other.rgb&& brightness == other.brightness;
        
            }

/// 律动模式（对应音乐页四个模式按钮）。
enum RhythmMode {
                    /// 单色律动：固定 base 色，亮度随音量。
single,
/// 七彩律动：15 色板循环，亮度随音量。
rainbow,
/// 强烈：七彩 + 亮度增益。
strong,
/// 柔和：七彩 + 亮度压缩。
soft,
                    ;
                    
                }
            