// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../error.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            Future<Uint8List>  hexToBytes({required String hex }) => RustLib.instance.api.crateApiProtocolHexToBytes(hex: hex);

Future<String>  bytesToHex({required List<int> bytes }) => RustLib.instance.api.crateApiProtocolBytesToHex(bytes: bytes);

Future<String>  dec2Hex({required BigInt n , required int width }) => RustLib.instance.api.crateApiProtocolDec2Hex(n: n, width: width);

Future<String>  littleEndian({required String hex }) => RustLib.instance.api.crateApiProtocolLittleEndian(hex: hex);

Future<String>  frameSeqHexLe({required int seq }) => RustLib.instance.api.crateApiProtocolFrameSeqHexLe(seq: seq);

Future<int>  crc32Hex({required String hex }) => RustLib.instance.api.crateApiProtocolCrc32Hex(hex: hex);

Future<int>  crc32Ieee({required List<int> data }) => RustLib.instance.api.crateApiProtocolCrc32Ieee(data: data);

/// AES-ECB 加密（API key），失败返回 [`WanError`]。
Future<String>  apiAesEncryptHex({required String plaintext }) => RustLib.instance.api.crateApiProtocolApiAesEncryptHex(plaintext: plaintext);

/// AES-ECB 解密（API key），失败返回 [`WanError`]。
Future<String>  apiAesDecryptHex({required String ciphertextHex }) => RustLib.instance.api.crateApiProtocolApiAesDecryptHex(ciphertextHex: ciphertextHex);

Future<String>  reportAesEncrypt({required String plaintext }) => RustLib.instance.api.crateApiProtocolReportAesEncrypt(plaintext: plaintext);

/// 设备上报解密，失败返回 [`WanError`]。
Future<String>  reportAesDecrypt({required String b64 }) => RustLib.instance.api.crateApiProtocolReportAesDecrypt(b64: b64);

Future<String>  buildPacket({required int seq , required String commandBodyHex }) => RustLib.instance.api.crateApiProtocolBuildPacket(seq: seq, commandBodyHex: commandBodyHex);

Future<String>  lightingCommandBody({required LightingEffect effect , required String colorHex , required int seed }) => RustLib.instance.api.crateApiProtocolLightingCommandBody(effect: effect, colorHex: colorHex, seed: seed);

/// LIGHT_FLASH_HEX 常量（座位绑定闪光特效，16 字节）。
Future<String>  lightFlashHex() => RustLib.instance.api.crateApiProtocolLightFlashHex();

Future<String>  seatWriteHex({int? lightArea , required int x1 , required int y1 , int? showNum }) => RustLib.instance.api.crateApiProtocolSeatWriteHex(lightArea: lightArea, x1: x1, y1: y1, showNum: showNum);

Future<String>  seatUnbindHex() => RustLib.instance.api.crateApiProtocolSeatUnbindHex();

Future<Uint8List>  antifakeInstruction({required int seq , required String macHex , required List<int> random16 }) => RustLib.instance.api.crateApiProtocolAntifakeInstruction(seq: seq, macHex: macHex, random16: random16);

Future<bool>  verifyAntifake({required List<int> message , required List<int> signature , required List<int> publicKey }) => RustLib.instance.api.crateApiProtocolVerifyAntifake(message: message, signature: signature, publicKey: publicKey);

Future<Uint8List>  buildAndroidBroadcast({required int seq , required String macHex , required int region , required int x0 , required int y0 , required int show_ }) => RustLib.instance.api.crateApiProtocolBuildAndroidBroadcast(seq: seq, macHex: macHex, region: region, x0: x0, y0: y0, show_: show_);

Future<IosBroadcastResult>  buildIosBroadcast({required int counter , required String macHex , required int region , required int x0 , required int y0 , required int show_ }) => RustLib.instance.api.crateApiProtocolBuildIosBroadcast(counter: counter, macHex: macHex, region: region, x0: x0, y0: y0, show_: show_);

Future<List<String>>  iosDataToServiceUuids({required List<int> data }) => RustLib.instance.api.crateApiProtocolIosDataToServiceUuids(data: data);

Future<Uint8List>  buildOtaModeSwitch() => RustLib.instance.api.crateApiProtocolBuildOtaModeSwitch();

Future<Uint8List>  buildOtaReboot() => RustLib.instance.api.crateApiProtocolBuildOtaReboot();

Future<Uint8List>  buildOtaFirmwarePacket({required int offset , required List<int> chunk }) => RustLib.instance.api.crateApiProtocolBuildOtaFirmwarePacket(offset: offset, chunk: chunk);

            /// iOS 广播结果（frmcnt + 26 字节数据）。
class IosBroadcastResult  {
                final int frmcnt;
final Uint8List data;

                const IosBroadcastResult({required this.frmcnt ,required this.data ,});

                
                

                
        @override
        int get hashCode => frmcnt.hashCode^data.hashCode;
        

                
        @override
        bool operator ==(Object other) =>
            identical(this, other) ||
            other is IosBroadcastResult &&
                runtimeType == other.runtimeType
                && frmcnt == other.frmcnt&& data == other.data;
        
            }

/// 9 种灯光效果。frb 生成对应 Dart 枚举。
enum LightingEffect {
                    blackScreen,
constantlyOn,
random,
flashMob,
blink,
breathe,
party,
rainbow,
starrySky,
                    ;
                    
                }
            