// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';


            // These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`


            /// hex 字符串 → 字节。
Future<Uint8List>  hexToBytes({required String hex }) => RustLib.instance.api.crateApiProtocolHexToBytes(hex: hex);

/// BLE 命令包：`[帧序号 4B LE][命令体 N B][CRC32 4B LE]`。
Future<String>  buildPacket({required int seq , required String commandBodyHex }) => RustLib.instance.api.crateApiProtocolBuildPacket(seq: seq, commandBodyHex: commandBodyHex);

/// 灯光效果命令体（随机源为 Party/Rainbow/Starry 等效果的 seed）。
Future<String>  lightingCommandBody({required LightingEffect effect , required String colorHex , required int seed }) => RustLib.instance.api.crateApiProtocolLightingCommandBody(effect: effect, colorHex: colorHex, seed: seed);

            /// 10 种灯光效果。frb 生成对应 Dart 枚举。
enum LightingEffect {
                    blackScreen,
constantlyOn,
random,
flashMob,
blink,
breathe,
party,
rainbow,
starrySky,
flow,
                    ;
                    
                }
            